### ISSUE TITLE
Short-link to waffle of user's assigned issues

### ISSUE THREAD

**Issue by mckaydavis** [CodeforHawaii/cfh.link#1]
I want a shortlink like mckaydavis.cfh.link to go to a waffle.io board filtered by that user's assigned issues.

**Comment by mckaydavis** [comment]
I setup a nginx redirect to the aggregated meta-repo waffle at https://waffle.io/codeforhawaii/issues?assigned=<username>

e.g.
http://mckaydavis.issues.cfh.link will show all issues in the CfH org assigned to me.

acceptance:
move the code from the docker container config file into the init.sh script and checkin

bugs:
The redirect does not work if the github username contains upper-case characters because of this waffle.io issue: https://waffle.io/waffleio/waffle.io/cards/5453ba807abdfe69daba5acb

**Comment by rbvea** [comment]
:+1:

**Comment by mckaydavis** [comment]
This works (save for the bug listed above). Not too sure how super-useful it is, but done.
